site_name: Fine-mapping Documentation
pages:
  - Introduction: 'index.md'
  - Data Preprocessing:
    - '1. File formatting': 'preprocessing/file_format.md'
    - '2. File splitting': 'preprocessing/file_split.md'
    - '3. LD matrix generation': 'preprocessing/ld_matrix_generation.md'
    - '4. Functional annotation generation': 'preprocessing/functional_annotation_generation.md'
  - Software Running: 'software_running.md'
  - Caviarbf Manual: 'caviarbf_manual.md'
  - Reference: 'reference.md'
theme: readthedocs
repo_name: https://github.com/hongchengyao/fine-mapping_document/tree/master
copyright: Copyright Â© 2018 Hongcheng Yao
markdown_extensions:
    - toc:
        permalink: True
markdown_extensions:
  - admonition